site:
  title: Continous Delivery
  url: /
  start_page: v0.10@continuous-delivery:en:index.adoc

content:
  sources:
    - url: https://github.com/rancher/fleet-product-docs.git
      branches: [main]
      start_paths: [versions/v0.10, versions/v0.9]


ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'