services:
  antora:
    build:
      context: .
      dockerfile: Dockerfile.antora
    image: local/antora
    container_name: antora
    user: 1000:1000
    volumes:
      - .:/antora
    command: ${PLAYBOOK:-playbook-local.yml}
    develop:
      watch:
        - path: ./docs/
          action: rebuild
  
  http-server:
    image: registry.opensuse.org/opensuse/bci/node:20
    container_name: http_server
    working_dir: /antora
    volumes:
      - ./build:/antora
    command: >
      sh -c "
      npm i -g http-server &&
      npx http-server site -c-1 -p 8080
      "
    ports:
      - "8080:8080"
