services:
  antora:
    build:
      context: .
      dockerfile: Dockerfile.antora
    image: local/antora_service
    container_name: antora_service
    user: 1000:1000
    volumes:
      - .:/antora
    environment:
      - PLAYBOOK
    command: sh -c "rm -rf build && antora --fetch ${PLAYBOOK:-playbook-remote.yml}"
  
  http-server:
    image: registry.opensuse.org/opensuse/bci/node:20
    container_name: http_server
    working_dir: /antora
    volumes:
      - .:/antora
    command: >
      sh -c "
      npm i -g http-server &&
      npx http-server build/site -c-1 -p 8080
      "
    ports:
      - "8080:8080"
