site:
  title: Rancher Turtles
  url: /
  start_page: v0.13@turtles:en:index.adoc

content:
  sources:
    - url: ./
      start_paths: [docs/v0.13, docs/v0.12, docs/v0.11]

# Description: SUSE UI bundle
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
    page-toclevels: 4@
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site